[package]
name = "jeeflow-demo-salvo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "jeeflow workflow engine demo server (Salvo)"

[dependencies]
jeeflow-core = { path = "../jeeflow-core", version = "1.0.0", features = ["dev-flows"] }
jeeflow-repository-sqlx = { path = "../jeeflow-repository-sqlx", version = "1.0.0" }
jeeflow-persist = { path = "../jeeflow-persist", version = "1.0.0" }
jeeflow-facade = { path = "../jeeflow-facade", version = "1.0.0" }
salvo = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
