[package]
name = "jeeflow-repository-sqlx"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "jeeflow workflow engine sqlx repository implementation"

[dependencies]
jeeflow-core = { path = "../jeeflow-core", version = "1.0.0" }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[features]
default = []
mysql-smoke = []
